/**
 * Generates supabase/functions/portfolio-chat/prompt.ts from the same data the
 * site renders (src/lib/resume.ts and src/lib/projects.ts), so the chatbot can
 * never drift from the pages again.
 *
 * Run:   npm run build:prompt
 * Check: npm run check:prompt   (fails when the committed file is stale)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { person, experience, leadership, skillGroups, sideProjects } from "../src/lib/resume";
import { publicProjects } from "../src/lib/projects";

const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../supabase/functions/portfolio-chat/prompt.ts");

function buildPrompt(): string {
  const work = experience
    .map((e) => `- **${e.org}** (${e.period}) — ${e.title}, ${e.location}\n  ${e.bullets.map((b) => `${b}.`).join(" ")}`)
    .join("\n");

  const lead = leadership
    .map((l) => `- **${l.org}** (${l.period}) — ${l.title}, ${l.location}\n  ${l.description}`)
    .join("\n");

  const projects = publicProjects()
    .map((p, i) => {
      const results = (p.keyResults ?? []).map((r) => `${r.value} ${r.label}`).join("; ");
      const gated = p.gated
        ? " This case study is shared by request only: describe it at this level of detail, never invent specifics, and point people to the passcode form on the page or to email."
        : "";
      return `${i + 1}. **${p.title}** (link: /project/${p.id}) — ${p.description} Role: ${p.role}. Timeline: ${p.timeline}. Tools: ${p.tools.join(", ")}. Results: ${results || p.outcomeMetrics}.${gated}`;
    })
    .join("\n");

  const skills = skillGroups.map((g) => `- ${g.label}: ${g.skills.join(", ")}`).join("\n");
  const side = sideProjects.map((s) => `- ${s.title}: ${s.description}`).join("\n");

  return `You are the assistant on Huruy Kidanemariam's portfolio site. You speak about Huruy in the third person ("Huruy designed...", "he shipped..."). You are warm, specific and concise, never salesy. Recruiters and hiring managers are your main audience.

## About Huruy
- ${person.title} and Builder, ${person.location}. ${person.yearsExperience} years of UX and product design experience.
- ${person.summary}
- ${person.availability}
- Self-directed builder who learns by shipping: designed, built and released EBT Finder on the iOS App Store solo. Designs in code, not just mockups. Top 1% designer on Lovable.
- Contact: ${person.email} | ${person.linkedinLabel} | ${person.websiteLabel}

## Work history
${work}

## Design leadership
${lead}

## Side projects
${side}

## Portfolio case studies
${projects}

## Skills
${skills}

## Rules
- When someone asks about a specific project, include a markdown link to its case study, for example [Read the EBT Finder case study](/project/ebtfinder).
- When asked for a resume, link to [Huruy's resume](/resume). For hiring questions, link to [the hiring page](/senior-ux-designer).
- When appropriate, suggest reaching out via the [contact page](/contact) or by email at ${person.email}.
- Politely decline off-topic questions: "I can only help with questions about Huruy's work and experience. What would you like to know?"
- Keep responses concise (2 to 4 short paragraphs). Use markdown for formatting. Do not use em dashes.
- Never make up information. Only share what is written above. If you don't know, say so and suggest emailing Huruy.`;
}

const prompt = buildPrompt();
const file = `// Generated by scripts/build-chat-prompt.ts from src/lib/resume.ts and src/lib/projects.ts.
// Do not edit by hand: run \`npm run build:prompt\`.
export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing file counts as stale */
  }
  if (current !== file) {
    console.error("supabase/functions/portfolio-chat/prompt.ts is out of date. Run: npm run build:prompt");
    process.exit(1);
  }
  console.log("chat prompt is up to date");
} else {
  writeFileSync(OUT, file);
  console.log(`wrote ${path.relative(process.cwd(), OUT)} (${prompt.length} chars)`);
}
