/**
 * One-off image optimizer: converts public/images/**.png to WebP (max 1600px wide),
 * builds the 1200x630 Open Graph PNG, and writes src/lib/imageDimensions.ts so
 * <img> tags can carry width/height and avoid layout shift.
 *
 * sharp is not a project dependency; run with:  npm i --no-save sharp && node scripts/optimize-images.mjs
 */
import { readdir, stat, writeFile, unlink } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = new URL("..", import.meta.url).pathname;
const IMAGES = path.join(ROOT, "public/images");
const MAX_WIDTH = 1600;

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

const dims = {};
for (const file of await walk(IMAGES)) {
  const ext = path.extname(file).toLowerCase();
  if (![".png", ".jpg", ".jpeg", ".webp", ".svg"].includes(ext)) continue;
  const target = file.replace(/\.(png|jpe?g)$/i, ".webp");
  if (ext !== ".webp" && ext !== ".svg") {
    const before = (await stat(file)).size;
    const img = sharp(file);
    const meta = await img.metadata();
    await img
      .resize({ width: Math.min(MAX_WIDTH, meta.width ?? MAX_WIDTH), withoutEnlargement: true })
      .webp({ quality: 82, effort: 6 })
      .toFile(target);
    const after = (await stat(target)).size;
    console.log(`${path.relative(ROOT, file)} ${(before / 1024).toFixed(0)} KB -> ${(after / 1024).toFixed(0)} KB`);
    await unlink(file);
  }
  const meta = await sharp(target).metadata();
  dims["/" + path.relative(path.join(ROOT, "public"), target)] = { width: meta.width, height: meta.height };
}

// Open Graph image: exactly 1200x630 PNG.
const og = path.join(ROOT, "public/og-image.png");
await sharp(og).resize(1200, 630, { fit: "cover", position: "centre" }).png({ compressionLevel: 9 }).toFile(og + ".tmp");
await sharp(og + ".tmp").toFile(og);
await unlink(og + ".tmp");
dims["/og-image.png"] = { width: 1200, height: 630 };

const entries = Object.keys(dims)
  .sort()
  .map((k) => `  "${k}": { width: ${dims[k].width}, height: ${dims[k].height} },`)
  .join("\n");
await writeFile(
  path.join(ROOT, "src/lib/imageDimensions.ts"),
  `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\nexport const imageDimensions: Record<string, { width: number; height: number }> = {\n${entries}\n};\n`,
);
console.log("wrote src/lib/imageDimensions.ts");
